[build]
  command = "dotnet publish src/PortalCT.Web/PortalCT.Web.csproj -c Release -o publish"
  publish = "publish/wwwroot"

[build.environment]
  DOTNET_CLI_TELEMETRY_OPTOUT = "1"
  ASPNETCORE_ENVIRONMENT = "Production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200