'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WebserviceVB
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://webservicect.casaeterra.com/", ConfigurationName:="WebserviceVB.loginSoap")>  _
    Public Interface loginSoap
        
        'CODEGEN: Gerando contrato de mensagem porque o nome do elemento nome no namespace http://webservicect.casaeterra.com/ não está marcado como nulo
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/loginad", ReplyAction:="*")>  _
        Function loginad(ByVal request As WebserviceVB.loginadRequest) As WebserviceVB.loginadResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/loginad", ReplyAction:="*")>  _
        Function loginadAsync(ByVal request As WebserviceVB.loginadRequest) As System.Threading.Tasks.Task(Of WebserviceVB.loginadResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o nome do elemento usuario no namespace http://webservicect.casaeterra.com/ não está marcado como nulo
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/getpermissoes", ReplyAction:="*")>  _
        Function getpermissoes(ByVal request As WebserviceVB.getpermissoesRequest) As WebserviceVB.getpermissoesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/getpermissoes", ReplyAction:="*")>  _
        Function getpermissoesAsync(ByVal request As WebserviceVB.getpermissoesRequest) As System.Threading.Tasks.Task(Of WebserviceVB.getpermissoesResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o nome do elemento cpf no namespace http://webservicect.casaeterra.com/ não está marcado como nulo
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/logincli", ReplyAction:="*")>  _
        Function logincli(ByVal request As WebserviceVB.logincliRequest) As WebserviceVB.logincliResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/logincli", ReplyAction:="*")>  _
        Function logincliAsync(ByVal request As WebserviceVB.logincliRequest) As System.Threading.Tasks.Task(Of WebserviceVB.logincliResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o nome do elemento cpf no namespace http://webservicect.casaeterra.com/ não está marcado como nulo
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/getboletos", ReplyAction:="*")>  _
        Function getboletos(ByVal request As WebserviceVB.getboletosRequest) As WebserviceVB.getboletosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/getboletos", ReplyAction:="*")>  _
        Function getboletosAsync(ByVal request As WebserviceVB.getboletosRequest) As System.Threading.Tasks.Task(Of WebserviceVB.getboletosResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o nome do elemento cpf no namespace http://webservicect.casaeterra.com/ não está marcado como nulo
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/Dadoscli", ReplyAction:="*")>  _
        Function Dadoscli(ByVal request As WebserviceVB.DadoscliRequest) As WebserviceVB.DadoscliResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/Dadoscli", ReplyAction:="*")>  _
        Function DadoscliAsync(ByVal request As WebserviceVB.DadoscliRequest) As System.Threading.Tasks.Task(Of WebserviceVB.DadoscliResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o nome do elemento cpf no namespace http://webservicect.casaeterra.com/ não está marcado como nulo
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/Gravaescri", ReplyAction:="*")>  _
        Function Gravaescri(ByVal request As WebserviceVB.GravaescriRequest) As WebserviceVB.GravaescriResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/Gravaescri", ReplyAction:="*")>  _
        Function GravaescriAsync(ByVal request As WebserviceVB.GravaescriRequest) As System.Threading.Tasks.Task(Of WebserviceVB.GravaescriResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o nome do elemento cpf no namespace http://webservicect.casaeterra.com/ não está marcado como nulo
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/Gravatransf", ReplyAction:="*")>  _
        Function Gravatransf(ByVal request As WebserviceVB.GravatransfRequest) As WebserviceVB.GravatransfResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/Gravatransf", ReplyAction:="*")>  _
        Function GravatransfAsync(ByVal request As WebserviceVB.GravatransfRequest) As System.Threading.Tasks.Task(Of WebserviceVB.GravatransfResponse)
        
        'CODEGEN: Gerando contrato de mensagem porque o nome do elemento empresa no namespace http://webservicect.casaeterra.com/ não está marcado como nulo
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/Statusobra", ReplyAction:="*")>  _
        Function Statusobra(ByVal request As WebserviceVB.StatusobraRequest) As WebserviceVB.StatusobraResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://webservicect.casaeterra.com/Statusobra", ReplyAction:="*")>  _
        Function StatusobraAsync(ByVal request As WebserviceVB.StatusobraRequest) As System.Threading.Tasks.Task(Of WebserviceVB.StatusobraResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class loginadRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="loginad", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.loginadRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.loginadRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class loginadRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nome As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public senha As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nome As String, ByVal senha As String)
            MyBase.New
            Me.nome = nome
            Me.senha = senha
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class loginadResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="loginadResponse", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.loginadResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.loginadResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class loginadResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public loginadResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal loginadResult As String)
            MyBase.New
            Me.loginadResult = loginadResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getpermissoesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getpermissoes", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.getpermissoesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.getpermissoesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class getpermissoesRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String)
            MyBase.New
            Me.usuario = usuario
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getpermissoesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getpermissoesResponse", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.getpermissoesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.getpermissoesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class getpermissoesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getpermissoesResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getpermissoesResult As String)
            MyBase.New
            Me.getpermissoesResult = getpermissoesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class logincliRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="logincli", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.logincliRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.logincliRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class logincliRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cpf As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public dtnasc As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public token As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cpf As String, ByVal dtnasc As String, ByVal token As String)
            MyBase.New
            Me.cpf = cpf
            Me.dtnasc = dtnasc
            Me.token = token
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class logincliResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="logincliResponse", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.logincliResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.logincliResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class logincliResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public logincliResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal logincliResult As String)
            MyBase.New
            Me.logincliResult = logincliResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getboletosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getboletos", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.getboletosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.getboletosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class getboletosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cpf As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public dtnasc As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public token As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cpf As String, ByVal dtnasc As String, ByVal token As String)
            MyBase.New
            Me.cpf = cpf
            Me.dtnasc = dtnasc
            Me.token = token
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getboletosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getboletosResponse", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.getboletosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.getboletosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class getboletosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getboletosResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getboletosResult As String)
            MyBase.New
            Me.getboletosResult = getboletosResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DadoscliRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Dadoscli", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.DadoscliRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.DadoscliRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class DadoscliRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cpf As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public token As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public wquitados As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cpf As String, ByVal token As String, ByVal wquitados As String)
            MyBase.New
            Me.cpf = cpf
            Me.token = token
            Me.wquitados = wquitados
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DadoscliResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DadoscliResponse", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.DadoscliResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.DadoscliResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class DadoscliResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DadoscliResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DadoscliResult As String)
            MyBase.New
            Me.DadoscliResult = DadoscliResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GravaescriRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Gravaescri", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.GravaescriRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.GravaescriRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class GravaescriRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cpf As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public cliente As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public obs As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public email As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public telefone As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public wprioridade As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public lote As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public token As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cpf As String, ByVal cliente As String, ByVal obs As String, ByVal email As String, ByVal telefone As String, ByVal wprioridade As String, ByVal lote As String, ByVal token As String)
            MyBase.New
            Me.cpf = cpf
            Me.cliente = cliente
            Me.obs = obs
            Me.email = email
            Me.telefone = telefone
            Me.wprioridade = wprioridade
            Me.lote = lote
            Me.token = token
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GravaescriResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GravaescriResponse", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.GravaescriResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.GravaescriResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class GravaescriResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GravaescriResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GravaescriResult As String)
            MyBase.New
            Me.GravaescriResult = GravaescriResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GravatransfRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Gravatransf", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.GravatransfRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.GravatransfRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class GravatransfRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cpf As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public cliente As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public obs As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public email As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public telefone As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public lote As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public token As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cpf As String, ByVal cliente As String, ByVal obs As String, ByVal email As String, ByVal telefone As String, ByVal lote As String, ByVal token As String)
            MyBase.New
            Me.cpf = cpf
            Me.cliente = cliente
            Me.obs = obs
            Me.email = email
            Me.telefone = telefone
            Me.lote = lote
            Me.token = token
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GravatransfResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GravatransfResponse", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.GravatransfResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.GravatransfResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class GravatransfResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GravatransfResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GravatransfResult As String)
            MyBase.New
            Me.GravatransfResult = GravatransfResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class StatusobraRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Statusobra", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.StatusobraRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.StatusobraRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class StatusobraRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public empresa As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public obra As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public token As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal empresa As String, ByVal obra As String, ByVal token As String)
            MyBase.New
            Me.empresa = empresa
            Me.obra = obra
            Me.token = token
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class StatusobraResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="StatusobraResponse", [Namespace]:="http://webservicect.casaeterra.com/", Order:=0)>  _
        Public Body As WebserviceVB.StatusobraResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WebserviceVB.StatusobraResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://webservicect.casaeterra.com/")>  _
    Partial Public Class StatusobraResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public StatusobraResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal StatusobraResult As String)
            MyBase.New
            Me.StatusobraResult = StatusobraResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface loginSoapChannel
        Inherits WebserviceVB.loginSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class loginSoapClient
        Inherits System.ServiceModel.ClientBase(Of WebserviceVB.loginSoap)
        Implements WebserviceVB.loginSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_loginad(ByVal request As WebserviceVB.loginadRequest) As WebserviceVB.loginadResponse Implements WebserviceVB.loginSoap.loginad
            Return MyBase.Channel.loginad(request)
        End Function
        
        Public Function loginad(ByVal nome As String, ByVal senha As String) As String
            Dim inValue As WebserviceVB.loginadRequest = New WebserviceVB.loginadRequest()
            inValue.Body = New WebserviceVB.loginadRequestBody()
            inValue.Body.nome = nome
            inValue.Body.senha = senha
            Dim retVal As WebserviceVB.loginadResponse = CType(Me,WebserviceVB.loginSoap).loginad(inValue)
            Return retVal.Body.loginadResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_loginadAsync(ByVal request As WebserviceVB.loginadRequest) As System.Threading.Tasks.Task(Of WebserviceVB.loginadResponse) Implements WebserviceVB.loginSoap.loginadAsync
            Return MyBase.Channel.loginadAsync(request)
        End Function
        
        Public Function loginadAsync(ByVal nome As String, ByVal senha As String) As System.Threading.Tasks.Task(Of WebserviceVB.loginadResponse)
            Dim inValue As WebserviceVB.loginadRequest = New WebserviceVB.loginadRequest()
            inValue.Body = New WebserviceVB.loginadRequestBody()
            inValue.Body.nome = nome
            inValue.Body.senha = senha
            Return CType(Me,WebserviceVB.loginSoap).loginadAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_getpermissoes(ByVal request As WebserviceVB.getpermissoesRequest) As WebserviceVB.getpermissoesResponse Implements WebserviceVB.loginSoap.getpermissoes
            Return MyBase.Channel.getpermissoes(request)
        End Function
        
        Public Function getpermissoes(ByVal usuario As String) As String
            Dim inValue As WebserviceVB.getpermissoesRequest = New WebserviceVB.getpermissoesRequest()
            inValue.Body = New WebserviceVB.getpermissoesRequestBody()
            inValue.Body.usuario = usuario
            Dim retVal As WebserviceVB.getpermissoesResponse = CType(Me,WebserviceVB.loginSoap).getpermissoes(inValue)
            Return retVal.Body.getpermissoesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_getpermissoesAsync(ByVal request As WebserviceVB.getpermissoesRequest) As System.Threading.Tasks.Task(Of WebserviceVB.getpermissoesResponse) Implements WebserviceVB.loginSoap.getpermissoesAsync
            Return MyBase.Channel.getpermissoesAsync(request)
        End Function
        
        Public Function getpermissoesAsync(ByVal usuario As String) As System.Threading.Tasks.Task(Of WebserviceVB.getpermissoesResponse)
            Dim inValue As WebserviceVB.getpermissoesRequest = New WebserviceVB.getpermissoesRequest()
            inValue.Body = New WebserviceVB.getpermissoesRequestBody()
            inValue.Body.usuario = usuario
            Return CType(Me,WebserviceVB.loginSoap).getpermissoesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_logincli(ByVal request As WebserviceVB.logincliRequest) As WebserviceVB.logincliResponse Implements WebserviceVB.loginSoap.logincli
            Return MyBase.Channel.logincli(request)
        End Function
        
        Public Function logincli(ByVal cpf As String, ByVal dtnasc As String, ByVal token As String) As String
            Dim inValue As WebserviceVB.logincliRequest = New WebserviceVB.logincliRequest()
            inValue.Body = New WebserviceVB.logincliRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.dtnasc = dtnasc
            inValue.Body.token = token
            Dim retVal As WebserviceVB.logincliResponse = CType(Me,WebserviceVB.loginSoap).logincli(inValue)
            Return retVal.Body.logincliResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_logincliAsync(ByVal request As WebserviceVB.logincliRequest) As System.Threading.Tasks.Task(Of WebserviceVB.logincliResponse) Implements WebserviceVB.loginSoap.logincliAsync
            Return MyBase.Channel.logincliAsync(request)
        End Function
        
        Public Function logincliAsync(ByVal cpf As String, ByVal dtnasc As String, ByVal token As String) As System.Threading.Tasks.Task(Of WebserviceVB.logincliResponse)
            Dim inValue As WebserviceVB.logincliRequest = New WebserviceVB.logincliRequest()
            inValue.Body = New WebserviceVB.logincliRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.dtnasc = dtnasc
            inValue.Body.token = token
            Return CType(Me,WebserviceVB.loginSoap).logincliAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_getboletos(ByVal request As WebserviceVB.getboletosRequest) As WebserviceVB.getboletosResponse Implements WebserviceVB.loginSoap.getboletos
            Return MyBase.Channel.getboletos(request)
        End Function
        
        Public Function getboletos(ByVal cpf As String, ByVal dtnasc As String, ByVal token As String) As String
            Dim inValue As WebserviceVB.getboletosRequest = New WebserviceVB.getboletosRequest()
            inValue.Body = New WebserviceVB.getboletosRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.dtnasc = dtnasc
            inValue.Body.token = token
            Dim retVal As WebserviceVB.getboletosResponse = CType(Me,WebserviceVB.loginSoap).getboletos(inValue)
            Return retVal.Body.getboletosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_getboletosAsync(ByVal request As WebserviceVB.getboletosRequest) As System.Threading.Tasks.Task(Of WebserviceVB.getboletosResponse) Implements WebserviceVB.loginSoap.getboletosAsync
            Return MyBase.Channel.getboletosAsync(request)
        End Function
        
        Public Function getboletosAsync(ByVal cpf As String, ByVal dtnasc As String, ByVal token As String) As System.Threading.Tasks.Task(Of WebserviceVB.getboletosResponse)
            Dim inValue As WebserviceVB.getboletosRequest = New WebserviceVB.getboletosRequest()
            inValue.Body = New WebserviceVB.getboletosRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.dtnasc = dtnasc
            inValue.Body.token = token
            Return CType(Me,WebserviceVB.loginSoap).getboletosAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_Dadoscli(ByVal request As WebserviceVB.DadoscliRequest) As WebserviceVB.DadoscliResponse Implements WebserviceVB.loginSoap.Dadoscli
            Return MyBase.Channel.Dadoscli(request)
        End Function
        
        Public Function Dadoscli(ByVal cpf As String, ByVal token As String, ByVal wquitados As String) As String
            Dim inValue As WebserviceVB.DadoscliRequest = New WebserviceVB.DadoscliRequest()
            inValue.Body = New WebserviceVB.DadoscliRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.token = token
            inValue.Body.wquitados = wquitados
            Dim retVal As WebserviceVB.DadoscliResponse = CType(Me,WebserviceVB.loginSoap).Dadoscli(inValue)
            Return retVal.Body.DadoscliResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_DadoscliAsync(ByVal request As WebserviceVB.DadoscliRequest) As System.Threading.Tasks.Task(Of WebserviceVB.DadoscliResponse) Implements WebserviceVB.loginSoap.DadoscliAsync
            Return MyBase.Channel.DadoscliAsync(request)
        End Function
        
        Public Function DadoscliAsync(ByVal cpf As String, ByVal token As String, ByVal wquitados As String) As System.Threading.Tasks.Task(Of WebserviceVB.DadoscliResponse)
            Dim inValue As WebserviceVB.DadoscliRequest = New WebserviceVB.DadoscliRequest()
            inValue.Body = New WebserviceVB.DadoscliRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.token = token
            inValue.Body.wquitados = wquitados
            Return CType(Me,WebserviceVB.loginSoap).DadoscliAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_Gravaescri(ByVal request As WebserviceVB.GravaescriRequest) As WebserviceVB.GravaescriResponse Implements WebserviceVB.loginSoap.Gravaescri
            Return MyBase.Channel.Gravaescri(request)
        End Function
        
        Public Function Gravaescri(ByVal cpf As String, ByVal cliente As String, ByVal obs As String, ByVal email As String, ByVal telefone As String, ByVal wprioridade As String, ByVal lote As String, ByVal token As String) As String
            Dim inValue As WebserviceVB.GravaescriRequest = New WebserviceVB.GravaescriRequest()
            inValue.Body = New WebserviceVB.GravaescriRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.cliente = cliente
            inValue.Body.obs = obs
            inValue.Body.email = email
            inValue.Body.telefone = telefone
            inValue.Body.wprioridade = wprioridade
            inValue.Body.lote = lote
            inValue.Body.token = token
            Dim retVal As WebserviceVB.GravaescriResponse = CType(Me,WebserviceVB.loginSoap).Gravaescri(inValue)
            Return retVal.Body.GravaescriResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_GravaescriAsync(ByVal request As WebserviceVB.GravaescriRequest) As System.Threading.Tasks.Task(Of WebserviceVB.GravaescriResponse) Implements WebserviceVB.loginSoap.GravaescriAsync
            Return MyBase.Channel.GravaescriAsync(request)
        End Function
        
        Public Function GravaescriAsync(ByVal cpf As String, ByVal cliente As String, ByVal obs As String, ByVal email As String, ByVal telefone As String, ByVal wprioridade As String, ByVal lote As String, ByVal token As String) As System.Threading.Tasks.Task(Of WebserviceVB.GravaescriResponse)
            Dim inValue As WebserviceVB.GravaescriRequest = New WebserviceVB.GravaescriRequest()
            inValue.Body = New WebserviceVB.GravaescriRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.cliente = cliente
            inValue.Body.obs = obs
            inValue.Body.email = email
            inValue.Body.telefone = telefone
            inValue.Body.wprioridade = wprioridade
            inValue.Body.lote = lote
            inValue.Body.token = token
            Return CType(Me,WebserviceVB.loginSoap).GravaescriAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_Gravatransf(ByVal request As WebserviceVB.GravatransfRequest) As WebserviceVB.GravatransfResponse Implements WebserviceVB.loginSoap.Gravatransf
            Return MyBase.Channel.Gravatransf(request)
        End Function
        
        Public Function Gravatransf(ByVal cpf As String, ByVal cliente As String, ByVal obs As String, ByVal email As String, ByVal telefone As String, ByVal lote As String, ByVal token As String) As String
            Dim inValue As WebserviceVB.GravatransfRequest = New WebserviceVB.GravatransfRequest()
            inValue.Body = New WebserviceVB.GravatransfRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.cliente = cliente
            inValue.Body.obs = obs
            inValue.Body.email = email
            inValue.Body.telefone = telefone
            inValue.Body.lote = lote
            inValue.Body.token = token
            Dim retVal As WebserviceVB.GravatransfResponse = CType(Me,WebserviceVB.loginSoap).Gravatransf(inValue)
            Return retVal.Body.GravatransfResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_GravatransfAsync(ByVal request As WebserviceVB.GravatransfRequest) As System.Threading.Tasks.Task(Of WebserviceVB.GravatransfResponse) Implements WebserviceVB.loginSoap.GravatransfAsync
            Return MyBase.Channel.GravatransfAsync(request)
        End Function
        
        Public Function GravatransfAsync(ByVal cpf As String, ByVal cliente As String, ByVal obs As String, ByVal email As String, ByVal telefone As String, ByVal lote As String, ByVal token As String) As System.Threading.Tasks.Task(Of WebserviceVB.GravatransfResponse)
            Dim inValue As WebserviceVB.GravatransfRequest = New WebserviceVB.GravatransfRequest()
            inValue.Body = New WebserviceVB.GravatransfRequestBody()
            inValue.Body.cpf = cpf
            inValue.Body.cliente = cliente
            inValue.Body.obs = obs
            inValue.Body.email = email
            inValue.Body.telefone = telefone
            inValue.Body.lote = lote
            inValue.Body.token = token
            Return CType(Me,WebserviceVB.loginSoap).GravatransfAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_Statusobra(ByVal request As WebserviceVB.StatusobraRequest) As WebserviceVB.StatusobraResponse Implements WebserviceVB.loginSoap.Statusobra
            Return MyBase.Channel.Statusobra(request)
        End Function
        
        Public Function Statusobra(ByVal empresa As String, ByVal obra As String, ByVal token As String) As String
            Dim inValue As WebserviceVB.StatusobraRequest = New WebserviceVB.StatusobraRequest()
            inValue.Body = New WebserviceVB.StatusobraRequestBody()
            inValue.Body.empresa = empresa
            inValue.Body.obra = obra
            inValue.Body.token = token
            Dim retVal As WebserviceVB.StatusobraResponse = CType(Me,WebserviceVB.loginSoap).Statusobra(inValue)
            Return retVal.Body.StatusobraResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WebserviceVB_loginSoap_StatusobraAsync(ByVal request As WebserviceVB.StatusobraRequest) As System.Threading.Tasks.Task(Of WebserviceVB.StatusobraResponse) Implements WebserviceVB.loginSoap.StatusobraAsync
            Return MyBase.Channel.StatusobraAsync(request)
        End Function
        
        Public Function StatusobraAsync(ByVal empresa As String, ByVal obra As String, ByVal token As String) As System.Threading.Tasks.Task(Of WebserviceVB.StatusobraResponse)
            Dim inValue As WebserviceVB.StatusobraRequest = New WebserviceVB.StatusobraRequest()
            inValue.Body = New WebserviceVB.StatusobraRequestBody()
            inValue.Body.empresa = empresa
            inValue.Body.obra = obra
            inValue.Body.token = token
            Return CType(Me,WebserviceVB.loginSoap).StatusobraAsync(inValue)
        End Function
    End Class
End Namespace
