'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace wsprotheus
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AURLACCESLIST", [Namespace]:="http://casaeterra.com"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AURLACCESLIST
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExtensionData1Field As wsprotheus.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AURLSField() As wsprotheus.AURL
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CDESCRIField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CMESSAGEField As String
        
        Private LSTATUSField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="ExtensionData", EmitDefaultValue:=false)>  _
        Public Property ExtensionData1() As wsprotheus.ExtensionDataObject
            Get
                Return Me.ExtensionData1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExtensionData1Field, value) <> true) Then
                    Me.ExtensionData1Field = value
                    Me.RaisePropertyChanged("ExtensionData1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property AURLS() As wsprotheus.AURL()
            Get
                Return Me.AURLSField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AURLSField, value) <> true) Then
                    Me.AURLSField = value
                    Me.RaisePropertyChanged("AURLS")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property CDESCRI() As String
            Get
                Return Me.CDESCRIField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CDESCRIField, value) <> true) Then
                    Me.CDESCRIField = value
                    Me.RaisePropertyChanged("CDESCRI")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property CMESSAGE() As String
            Get
                Return Me.CMESSAGEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CMESSAGEField, value) <> true) Then
                    Me.CMESSAGEField = value
                    Me.RaisePropertyChanged("CMESSAGE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property LSTATUS() As Boolean
            Get
                Return Me.LSTATUSField
            End Get
            Set
                If (Me.LSTATUSField.Equals(value) <> true) Then
                    Me.LSTATUSField = value
                    Me.RaisePropertyChanged("LSTATUS")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ExtensionDataObject", [Namespace]:="http://casaeterra.com"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ExtensionDataObject
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AURL", [Namespace]:="http://casaeterra.com"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AURL
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExtensionData1Field As wsprotheus.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CTITLEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CURLField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="ExtensionData", EmitDefaultValue:=false)>  _
        Public Property ExtensionData1() As wsprotheus.ExtensionDataObject
            Get
                Return Me.ExtensionData1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExtensionData1Field, value) <> true) Then
                    Me.ExtensionData1Field = value
                    Me.RaisePropertyChanged("ExtensionData1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property CTITLE() As String
            Get
                Return Me.CTITLEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CTITLEField, value) <> true) Then
                    Me.CTITLEField = value
                    Me.RaisePropertyChanged("CTITLE")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property CURL() As String
            Get
                Return Me.CURLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CURLField, value) <> true) Then
                    Me.CURLField = value
                    Me.RaisePropertyChanged("CURL")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://casaeterra.com", ConfigurationName:="wsprotheus.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Gerando contrato de mensagem porque o nome do elemento cLogin no namespace http://casaeterra.com não está marcado como nulo
        <System.ServiceModel.OperationContractAttribute(Action:="http://casaeterra.com/GetUrls", ReplyAction:="*")>  _
        Function GetUrls(ByVal request As wsprotheus.GetUrlsRequest) As wsprotheus.GetUrlsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://casaeterra.com/GetUrls", ReplyAction:="*")>  _
        Function GetUrlsAsync(ByVal request As wsprotheus.GetUrlsRequest) As System.Threading.Tasks.Task(Of wsprotheus.GetUrlsResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUrlsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUrls", [Namespace]:="http://casaeterra.com", Order:=0)>  _
        Public Body As wsprotheus.GetUrlsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsprotheus.GetUrlsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://casaeterra.com")>  _
    Partial Public Class GetUrlsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cLogin As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public cPassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public cToken As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cLogin As String, ByVal cPassword As String, ByVal cToken As String)
            MyBase.New
            Me.cLogin = cLogin
            Me.cPassword = cPassword
            Me.cToken = cToken
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetUrlsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetUrlsResponse", [Namespace]:="http://casaeterra.com", Order:=0)>  _
        Public Body As wsprotheus.GetUrlsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As wsprotheus.GetUrlsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://casaeterra.com")>  _
    Partial Public Class GetUrlsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetUrlsResult As wsprotheus.AURLACCESLIST
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetUrlsResult As wsprotheus.AURLACCESLIST)
            MyBase.New
            Me.GetUrlsResult = GetUrlsResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits wsprotheus.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of wsprotheus.ServiceSoap)
        Implements wsprotheus.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsprotheus_ServiceSoap_GetUrls(ByVal request As wsprotheus.GetUrlsRequest) As wsprotheus.GetUrlsResponse Implements wsprotheus.ServiceSoap.GetUrls
            Return MyBase.Channel.GetUrls(request)
        End Function
        
        Public Function GetUrls(ByVal cLogin As String, ByVal cPassword As String, ByVal cToken As String) As wsprotheus.AURLACCESLIST
            Dim inValue As wsprotheus.GetUrlsRequest = New wsprotheus.GetUrlsRequest()
            inValue.Body = New wsprotheus.GetUrlsRequestBody()
            inValue.Body.cLogin = cLogin
            inValue.Body.cPassword = cPassword
            inValue.Body.cToken = cToken
            Dim retVal As wsprotheus.GetUrlsResponse = CType(Me,wsprotheus.ServiceSoap).GetUrls(inValue)
            Return retVal.Body.GetUrlsResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wsprotheus_ServiceSoap_GetUrlsAsync(ByVal request As wsprotheus.GetUrlsRequest) As System.Threading.Tasks.Task(Of wsprotheus.GetUrlsResponse) Implements wsprotheus.ServiceSoap.GetUrlsAsync
            Return MyBase.Channel.GetUrlsAsync(request)
        End Function
        
        Public Function GetUrlsAsync(ByVal cLogin As String, ByVal cPassword As String, ByVal cToken As String) As System.Threading.Tasks.Task(Of wsprotheus.GetUrlsResponse)
            Dim inValue As wsprotheus.GetUrlsRequest = New wsprotheus.GetUrlsRequest()
            inValue.Body = New wsprotheus.GetUrlsRequestBody()
            inValue.Body.cLogin = cLogin
            inValue.Body.cPassword = cPassword
            inValue.Body.cToken = cToken
            Return CType(Me,wsprotheus.ServiceSoap).GetUrlsAsync(inValue)
        End Function
    End Class
End Namespace
